// Business types configuration with associated photo tags
// Each business type has predefined photo categories that clients can use

export const businessTypes = [
  "fitness",
  "restaurant",
  "retail",
  "professional_services",
  "ecommerce",
  "real_estate",
  "salon_spa",
  "healthcare",
  "construction",
  "creative_agency",
  "nonprofit",
  "education",
  "reiki",
  "photography",
  "automotive",
  "legal",
  "financial",
  "tech_startup",
  "hospitality",
  "pet_services",
  "wedding_events",
  "music_entertainment",
  "other",
] as const;

export type BusinessType = (typeof businessTypes)[number];

// Human-readable labels for business types
export const businessTypeLabels: Record<BusinessType, string> = {
  fitness: "Fitness / Gym",
  restaurant: "Restaurant / Food Service",
  retail: "Retail Store",
  professional_services: "Professional Services",
  ecommerce: "E-commerce",
  real_estate: "Real Estate",
  salon_spa: "Salon / Spa",
  healthcare: "Healthcare",
  construction: "Construction / Trades",
  creative_agency: "Creative Agency",
  nonprofit: "Nonprofit",
  education: "Education",
  reiki: "Reiki / Energy Healing",
  photography: "Photography / Videography",
  automotive: "Automotive",
  legal: "Legal Services",
  financial: "Financial Services",
  tech_startup: "Tech / Startup",
  hospitality: "Hospitality / Hotel",
  pet_services: "Pet Services",
  wedding_events: "Wedding / Events",
  music_entertainment: "Music / Entertainment",
  other: "Other",
};

// Comprehensive photo tag presets for each business type
// These are the suggested/default tags that appear for clients when uploading photos
export const businessPhotoTags: Record<BusinessType, string[]> = {
  fitness: [
    "trainer-headshot",
    "trainer-action",
    "facility-interior",
    "facility-exterior",
    "equipment",
    "group-classes",
    "personal-training",
    "members",
    "events",
    "before-after",
    "locker-room",
    "cardio-area",
    "weight-room",
    "studio",
    "pool",
    "reception",
    "merchandise",
    "nutrition",
    "testimonials",
    "social-media",
  ],
  restaurant: [
    "food-dishes",
    "food-closeup",
    "drinks-cocktails",
    "drinks-wine",
    "interior-dining",
    "interior-bar",
    "exterior-storefront",
    "exterior-patio",
    "kitchen",
    "team-chef",
    "team-staff",
    "events-private",
    "events-live",
    "menu-items",
    "ambiance-day",
    "ambiance-night",
    "ingredients",
    "plating",
    "desserts",
    "seasonal-specials",
  ],
  retail: [
    "products-featured",
    "products-new",
    "products-bestseller",
    "storefront",
    "interior-wide",
    "interior-displays",
    "team-headshots",
    "team-action",
    "window-displays",
    "seasonal",
    "events",
    "customers",
    "behind-scenes",
    "packaging",
    "checkout",
    "fitting-room",
    "signage",
    "lifestyle",
    "flat-lay",
    "social-media",
  ],
  professional_services: [
    "team-headshots",
    "team-group",
    "team-candid",
    "office-exterior",
    "office-reception",
    "office-workspace",
    "conference-room",
    "meetings",
    "events-networking",
    "events-conference",
    "clients",
    "awards",
    "community",
    "presentations",
    "technology",
    "documents",
    "branding",
    "testimonials",
    "leadership",
    "culture",
  ],
  ecommerce: [
    "products-hero",
    "products-detail",
    "products-lifestyle",
    "products-scale",
    "packaging-unboxing",
    "packaging-shipping",
    "branding-logo",
    "branding-materials",
    "flat-lay",
    "behind-scenes",
    "team",
    "warehouse",
    "manufacturing",
    "ingredients",
    "texture",
    "color-variants",
    "size-comparison",
    "in-use",
    "customer-photos",
    "social-content",
  ],
  real_estate: [
    "property-exterior",
    "property-interior",
    "property-aerial",
    "living-room",
    "kitchen",
    "bedroom",
    "bathroom",
    "outdoor-space",
    "staging",
    "agent-headshot",
    "agent-action",
    "team",
    "open-house",
    "neighborhood",
    "amenities",
    "virtual-tour",
    "floor-plans",
    "sold",
    "testimonials",
    "signage",
  ],
  salon_spa: [
    "services-hair",
    "services-nails",
    "services-skincare",
    "services-massage",
    "before-after-hair",
    "before-after-skin",
    "before-after-nails",
    "team-stylists",
    "team-estheticians",
    "interior-stations",
    "interior-treatment",
    "interior-waiting",
    "products-retail",
    "products-professional",
    "ambiance",
    "details",
    "events",
    "branding",
    "testimonials",
    "social-media",
  ],
  healthcare: [
    "facility-exterior",
    "facility-reception",
    "facility-waiting",
    "treatment-rooms",
    "equipment-medical",
    "team-doctors",
    "team-nurses",
    "team-staff",
    "technology",
    "patient-care",
    "community",
    "wellness",
    "education",
    "certifications",
    "testimonials",
    "accessibility",
    "pharmacy",
    "lab",
    "specialty",
    "branding",
  ],
  construction: [
    "projects-residential",
    "projects-commercial",
    "projects-renovation",
    "before-after",
    "progress-shots",
    "completed-exterior",
    "completed-interior",
    "team-crew",
    "team-leadership",
    "equipment-heavy",
    "equipment-tools",
    "materials",
    "safety",
    "craftsmanship",
    "blueprints",
    "client-meetings",
    "signage",
    "fleet",
    "testimonials",
    "certifications",
  ],
  creative_agency: [
    "portfolio-web",
    "portfolio-print",
    "portfolio-branding",
    "portfolio-video",
    "team-headshots",
    "team-creative",
    "workspace-office",
    "workspace-studio",
    "process-brainstorm",
    "process-design",
    "clients-logos",
    "clients-testimonials",
    "events-launch",
    "events-workshop",
    "behind-scenes",
    "awards",
    "culture",
    "equipment",
    "mood-boards",
    "presentations",
  ],
  nonprofit: [
    "mission-impact",
    "mission-story",
    "team-leadership",
    "team-staff",
    "events-fundraising",
    "events-community",
    "community-served",
    "volunteers",
    "programs-active",
    "programs-results",
    "partners",
    "donors",
    "facilities",
    "outreach",
    "education",
    "advocacy",
    "testimonials",
    "media",
    "annual-report",
    "branding",
  ],
  education: [
    "campus-exterior",
    "campus-grounds",
    "classrooms",
    "library",
    "labs",
    "students-learning",
    "students-activities",
    "faculty-headshots",
    "faculty-teaching",
    "staff",
    "events-graduation",
    "events-sports",
    "events-arts",
    "facilities-gym",
    "facilities-cafeteria",
    "technology",
    "clubs",
    "alumni",
    "testimonials",
    "branding",
  ],
  reiki: [
    "practitioner-headshot",
    "practitioner-session",
    "healing-space",
    "treatment-room",
    "crystals",
    "meditation-space",
    "workshops",
    "certifications",
    "testimonials",
    "chakra-work",
    "energy-healing",
    "relaxation",
    "nature",
    "sacred-objects",
    "candles-incense",
    "sound-healing",
    "group-sessions",
    "online-sessions",
    "educational",
    "branding",
  ],
  photography: [
    "portfolio-wedding",
    "portfolio-portrait",
    "portfolio-commercial",
    "portfolio-event",
    "portfolio-product",
    "behind-scenes",
    "equipment-cameras",
    "equipment-lighting",
    "studio-space",
    "on-location",
    "team-photographers",
    "team-assistants",
    "editing-process",
    "client-sessions",
    "testimonials",
    "awards",
    "workshops",
    "prints",
    "albums",
    "branding",
  ],
  automotive: [
    "vehicles-inventory",
    "vehicles-featured",
    "vehicles-detail",
    "showroom",
    "lot-exterior",
    "service-bay",
    "team-sales",
    "team-service",
    "team-leadership",
    "customer-delivery",
    "before-after",
    "parts",
    "accessories",
    "detailing",
    "test-drives",
    "financing",
    "certifications",
    "testimonials",
    "events",
    "branding",
  ],
  legal: [
    "attorney-headshots",
    "attorney-action",
    "team-partners",
    "team-associates",
    "team-staff",
    "office-exterior",
    "office-reception",
    "office-conference",
    "office-library",
    "courtroom",
    "client-meetings",
    "community",
    "awards",
    "publications",
    "speaking",
    "pro-bono",
    "testimonials",
    "certifications",
    "technology",
    "branding",
  ],
  financial: [
    "advisor-headshots",
    "advisor-meetings",
    "team-leadership",
    "team-analysts",
    "office-exterior",
    "office-interior",
    "conference-rooms",
    "technology",
    "client-meetings",
    "presentations",
    "seminars",
    "community",
    "awards",
    "certifications",
    "publications",
    "market-data",
    "testimonials",
    "compliance",
    "security",
    "branding",
  ],
  tech_startup: [
    "product-screenshots",
    "product-demo",
    "product-features",
    "team-founders",
    "team-engineers",
    "team-all-hands",
    "office-workspace",
    "office-collaboration",
    "office-amenities",
    "culture-events",
    "culture-perks",
    "investors",
    "customers",
    "conferences",
    "hackathons",
    "awards",
    "press",
    "swag",
    "roadmap",
    "branding",
  ],
  hospitality: [
    "rooms-standard",
    "rooms-suite",
    "rooms-detail",
    "lobby",
    "exterior-day",
    "exterior-night",
    "restaurant",
    "bar-lounge",
    "pool",
    "spa",
    "fitness",
    "meeting-rooms",
    "events-wedding",
    "events-corporate",
    "team-concierge",
    "team-housekeeping",
    "amenities",
    "local-area",
    "testimonials",
    "branding",
  ],
  pet_services: [
    "pets-dogs",
    "pets-cats",
    "pets-exotic",
    "facility-interior",
    "facility-exterior",
    "grooming-before-after",
    "grooming-process",
    "boarding-rooms",
    "play-areas",
    "team-groomers",
    "team-trainers",
    "team-caregivers",
    "training-sessions",
    "daycare",
    "products",
    "events",
    "testimonials",
    "certifications",
    "transport",
    "branding",
  ],
  wedding_events: [
    "ceremonies",
    "receptions",
    "decor-floral",
    "decor-lighting",
    "decor-table",
    "venues-indoor",
    "venues-outdoor",
    "couples",
    "bridal-party",
    "guests",
    "food-cake",
    "food-catering",
    "entertainment",
    "team-planners",
    "team-coordinators",
    "behind-scenes",
    "details",
    "testimonials",
    "portfolio",
    "branding",
  ],
  music_entertainment: [
    "performers-headshots",
    "performers-action",
    "performances-live",
    "performances-studio",
    "venues",
    "equipment",
    "merchandise",
    "fans-crowds",
    "backstage",
    "rehearsals",
    "recording",
    "music-videos",
    "album-artwork",
    "press-photos",
    "interviews",
    "awards",
    "collaborations",
    "events",
    "social-content",
    "branding",
  ],
  other: [
    "team-headshots",
    "team-group",
    "facility-interior",
    "facility-exterior",
    "products",
    "services",
    "events",
    "customers",
    "behind-scenes",
    "process",
    "results",
    "testimonials",
    "community",
    "awards",
    "certifications",
    "technology",
    "branding",
    "social-media",
    "marketing",
    "lifestyle",
  ],
};

// Get photo tags for a business type (with fallback to "other")
export function getPhotoTagsForBusinessType(businessType: BusinessType | string | null): string[] {
  if (!businessType) return businessPhotoTags.other;
  return businessPhotoTags[businessType as BusinessType] || businessPhotoTags.other;
}

// Format tag for display (convert kebab-case to Title Case)
export function formatTagLabel(tag: string): string {
  return tag
    .split("-")
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
